export { default as Login } from './login'
export { default as Inicial } from './inicial'
export { default as Home } from './home'
export { default as Produtos } from './produtos'
export { default as Dashboard } from './dashboard'
export { default as ListaProdutos } from './cadastroProduto'
export { default as ListaUsuarios } from './cadastroUsuario'
